//! EAC-FR-33 — the line observer, the vendor activity readers, and delivery while a run is going.

use super::*;

/// EAC-FR-32 — the line reassembler: line endings in both spellings, a last
/// line with no ending at all, and a line that will not end.
///
/// Exercised through the real runtime driver over a real pipe rather than
/// through the double, because the reassembly is the runtime's and a double
/// that replayed lines would be asserting itself.
#[test]
fn the_observer_is_handed_whole_lines_however_the_child_writes_them() {
    #[derive(Default)]
    struct Lines(StdMutex<Vec<(String, bool)>>);
    impl StreamObserver for Lines {
        fn line(&self, channel: StreamChannel, bytes: &[u8], whole: bool) {
            self.0.lock().unwrap().push((
                format!("{}:{}", channel.as_str(), String::from_utf8_lossy(bytes)),
                whole,
            ));
        }
    }

    let observer = Lines::default();
    let script = concat!(
        "printf 'first\\r\\nsecond\\n' ; ",
        // Deliberately unterminated: a CLI killed mid-line, and a CLI whose
        // last word has no newline after it, both end like this.
        "printf 'third-no-newline' ; ",
        "printf 'a diagnostic\\n' 1>&2"
    );
    let runtime = HostDockerCli::with_program("/bin/sh");
    let outcome = block_on(runtime.run(RunRequest {
        argv: &["-c".to_string(), script.to_string()],
        container: None,
        env: &BTreeMap::new(),
        stdin: b"",
        timeout: Duration::from_secs(20),
        cancel: CancellationToken::new(),
        stdout_limit: 4096,
        stderr_limit: 4096,
        observer: Some(&observer),
    }))
    .expect("the child ran");
    assert_eq!(outcome.exit_code, Some(0));

    let lines = observer.0.lock().unwrap().clone();
    assert!(
        lines.contains(&("stdout:first".to_string(), true)),
        "a CRLF ending left its carriage return on the line: {lines:?}"
    );
    assert!(lines.contains(&("stdout:second".to_string(), true)));
    // What the child wrote after its last line ending is still something it
    // said, and it arrives at EOF rather than being dropped.
    assert!(lines.contains(&("stdout:third-no-newline".to_string(), true)));
    assert!(lines.contains(&("stderr:a diagnostic".to_string(), true)));
    // The captured stream is unchanged by anybody watching it.
    assert_eq!(
        String::from_utf8_lossy(&outcome.stdout.bytes),
        "first\r\nsecond\nthird-no-newline"
    );
}

/// EAC-FR-32 — a line that will not end is delivered at the bound rather than
/// held for ever, and is marked as the piece it is.
#[test]
fn a_line_that_never_ends_is_delivered_at_the_bound() {
    // Only stdout: both streams reach end of stream, and the empty
    // end-of-stream delivery on the silent one would otherwise be counted here
    // as if the child had written it.
    #[derive(Default)]
    struct Pieces(StdMutex<Vec<(usize, bool)>>);
    impl StreamObserver for Pieces {
        fn line(&self, channel: StreamChannel, bytes: &[u8], whole: bool) {
            if channel == StreamChannel::Stdout {
                self.0.lock().unwrap().push((bytes.len(), whole));
            }
        }
    }

    let observer = Pieces::default();
    // Two and a bit times the bound, with no newline anywhere in it.
    let count = LIMIT_OBSERVED_LINE * 2 + 100;
    let runtime = HostDockerCli::with_program("/bin/sh");
    block_on(runtime.run(RunRequest {
        // Generated by the shell rather than passed as arguments: a
        // half-million-argument command line is near `ARG_MAX` on some systems
        // and slow on all of them.
        argv: &[
            "-c".to_string(),
            format!("head -c {count} /dev/zero | tr '\\0' 'y'"),
        ],
        container: None,
        env: &BTreeMap::new(),
        stdin: b"",
        timeout: Duration::from_secs(60),
        cancel: CancellationToken::new(),
        stdout_limit: count * 2,
        stderr_limit: 4096,
        observer: Some(&observer),
    }))
    .expect("the child ran");

    let pieces = observer.0.lock().unwrap().clone();
    let bounded: Vec<_> = pieces.iter().filter(|(_, whole)| !whole).collect();
    assert_eq!(bounded.len(), 2, "the bound did not hold: {pieces:?}");
    assert!(bounded.iter().all(|(len, _)| *len == LIMIT_OBSERVED_LINE));
    // And the remainder arrives at end of stream as the last thing the child
    // said, marked whole because it is the end of what there was.
    assert_eq!(pieces.last(), Some(&(100, true)));
}

/// CCP-FR-27 — Claude Code's event stream, read as activity.
///
/// Every event type this protocol names, and the ones it does not. What is
/// asserted is the *kind*, because that is what a reader scans a column of, and
/// the part of the summary that could only have come from the event's own
/// fields.
#[test]
fn claude_codes_events_are_read_as_activity() {
    let read = |value: serde_json::Value| descriptor::CLAUDE_CODE.activity(&value.to_string());
    use descriptor::ActivityKind as K;

    let started = read(json!({
        "type": "system", "subtype": "init", "model": "claude-sonnet-5",
        "tools": ["Read", "Write", "Bash"]
    }));
    assert_eq!(started.kind, K::Started);
    assert!(started.summary.contains("claude-sonnet-5"));
    assert!(started.summary.contains('3'), "the tool count is what says how much this agent can reach");

    // The single most useful line this CLI writes when a run is going nowhere:
    // a wrong or expired credential is ten of these and then a failure, and
    // without them the whole delay looks like thinking.
    let retry = read(json!({
        "type": "system", "subtype": "api_retry", "attempt": 3, "max_retries": 10,
        "error_status": 401, "error": "authentication_failed"
    }));
    assert_eq!(retry.kind, K::Retry);
    assert!(retry.summary.contains("3/10"));
    assert!(retry.summary.contains("401"));
    assert!(retry.summary.contains("authentication_failed"));

    let message = read(json!({
        "type": "assistant",
        "message": { "content": [{ "type": "text", "text": "reading the spec" }] }
    }));
    assert_eq!(message.kind, K::Message);
    assert_eq!(message.summary, "reading the spec");

    let thinking = read(json!({
        "type": "assistant",
        "message": { "content": [{ "type": "thinking", "thinking": "weighing it up" }] }
    }));
    assert_eq!(thinking.kind, K::Reasoning);
    assert!(thinking.summary.contains("weighing it up"));

    // A tool call names the tool and what it is about, which is the part a
    // reader follows.
    let call = read(json!({
        "type": "assistant",
        "message": { "content": [
            { "type": "text", "text": "let me look" },
            { "type": "tool_use", "name": "Read", "input": { "file_path": "/workspace/spec.md" } }
        ] }
    }));
    assert_eq!(call.kind, K::ToolCall);
    assert!(call.summary.contains("let me look"), "the prose beside a call was dropped");
    assert!(call.summary.contains("Read(/workspace/spec.md)"));

    let result = read(json!({
        "type": "user",
        "message": { "content": [{ "type": "tool_result", "is_error": true }] }
    }));
    assert_eq!(result.kind, K::ToolResult);
    assert!(result.summary.contains("failed"));

    let finished = read(json!({
        "type": "result", "subtype": "success", "is_error": false,
        "num_turns": 7, "duration_ms": 12345
    }));
    assert_eq!(finished.kind, K::Finished);
    assert!(finished.summary.contains('7') && finished.summary.contains("12345"));

    // CCP-FR-12: a failure inside the run is printed as the result under exit
    // zero, so the flag is the only thing separating this from a turn that
    // worked — and a reader must see it as a failure.
    let failed = read(json!({
        "type": "result", "subtype": "success", "is_error": true,
        "api_error_status": 401, "num_turns": 1, "duration_ms": 5
    }));
    assert_eq!(failed.kind, K::Error);
    assert!(failed.summary.contains("is_error"));
    assert!(failed.summary.contains("401"));

    // Never silent: an event this build has never seen, and a line that is not
    // JSON at all, both reach a reader as themselves.
    let future = read(json!({ "type": "some_future_event", "detail": "MARKER" }));
    assert_eq!(future.kind, K::Unrecognized);
    assert!(future.summary.contains("MARKER"));
    let prose = descriptor::CLAUDE_CODE.activity("not json at all");
    assert_eq!(prose.kind, K::Unrecognized);
    assert_eq!(prose.summary, "not json at all");
    assert_eq!(
        descriptor::CLAUDE_CODE.activity("").kind,
        K::Unrecognized,
        "an empty line still yields an activity rather than panicking"
    );

    // A summary is a row, and a row is bounded however much the agent wrote.
    let huge = read(json!({
        "type": "assistant",
        "message": { "content": [{ "type": "text", "text": "z".repeat(10_000) }] }
    }));
    assert!(huge.summary.chars().count() <= descriptor::LIMIT_SUMMARY_LINE + 1);
    // And collapsed to one line, so one event is one row.
    assert!(!huge.summary.contains('\n'));
    let multiline = read(json!({
        "type": "assistant",
        "message": { "content": [{ "type": "text", "text": "one\ntwo\nthree" }] }
    }));
    assert_eq!(multiline.summary, "one two three");
}

/// CDX-FR-28 — Codex's event stream, read as activity.
#[test]
fn codexs_events_are_read_as_activity() {
    let read = |value: serde_json::Value| descriptor::CODEX.activity(&value.to_string());
    use descriptor::ActivityKind as K;

    assert_eq!(
        read(json!({ "type": "thread.started", "thread_id": "t-1" })).kind,
        K::Started
    );
    assert_eq!(read(json!({ "type": "turn.started" })).kind, K::Started);

    let completed = read(json!({
        "type": "turn.completed",
        "usage": { "input_tokens": 120, "cached_input_tokens": 40, "output_tokens": 8 }
    }));
    assert_eq!(completed.kind, K::Finished);
    assert!(completed.summary.contains("120") && completed.summary.contains('8'));

    let failed = read(json!({
        "type": "turn.failed", "error": { "message": "the model refused" }
    }));
    assert_eq!(failed.kind, K::Error);
    assert!(failed.summary.contains("the model refused"));

    // CDX-FR-15: a top-level error event is a diagnostic on the stream rather
    // than the turn ending, and it still has to reach a reader.
    let notice = read(json!({ "type": "error", "message": "reconnecting" }));
    assert_eq!(notice.kind, K::Error);
    assert!(notice.summary.contains("reconnecting"));

    let command = read(json!({
        "type": "item.completed",
        "item": {
            "id": "i1", "type": "command_execution", "command": "cargo test",
            "status": "completed", "exit_code": 0
        }
    }));
    assert_eq!(command.kind, K::Command);
    assert!(command.summary.contains("$ cargo test"));
    assert!(command.summary.contains("exit 0"));

    let changed = read(json!({
        "type": "item.completed",
        "item": { "id": "i2", "type": "file_change", "changes": [1, 2, 3], "status": "completed" }
    }));
    assert_eq!(changed.kind, K::FileChange);
    assert!(changed.summary.contains('3'));

    let tool = read(json!({
        "type": "item.completed",
        "item": { "id": "i3", "type": "mcp_tool_call", "server": "fs", "tool": "read" }
    }));
    assert_eq!(tool.kind, K::ToolCall);
    assert_eq!(tool.summary, "fs.read");

    // A started item is the same item mid-flight, and says so rather than
    // reading as one that finished.
    let inflight = read(json!({
        "type": "item.started",
        "item": { "id": "i4", "type": "agent_message", "text": "thinking about it" }
    }));
    assert_eq!(inflight.kind, K::Message);
    assert!(inflight.summary.ends_with('…'));

    let unknown = read(json!({
        "type": "item.completed", "item": { "id": "i5", "type": "some_future_item" }
    }));
    assert_eq!(unknown.kind, K::Unrecognized);
    assert_eq!(descriptor::CODEX.activity("{ not json").kind, K::Unrecognized);
}

/// EAC-FR-11 / EAC-FR-12 — neither vendor module reads the other, including for
/// the activity reader.
///
/// The shared helper it needed had to go somewhere shared rather than into one
/// of the two, or an upgrade to either protocol would stop being a change to one
/// file.
#[test]
fn neither_vendor_module_reaches_into_the_other() {
    let claude = include_str!("../descriptor/claude_code.rs");
    let codex = include_str!("../descriptor/codex.rs");
    assert!(!claude.contains("codex::"), "the Claude module reads Codex's");
    assert!(
        !codex.contains("claude_code::"),
        "the Codex module reads Claude Code's"
    );
    // And neither names the other's grammar.
    for forbidden in ["stream-json", "--verbose", "--json-schema", "--permission-mode"] {
        assert!(
            !codex.contains(forbidden),
            "the Codex module names {forbidden}, which belongs to another vendor"
        );
    }
    for forbidden in ["exec resume", "danger-full-access", "model_reasoning_effort"] {
        assert!(
            !claude.contains(forbidden),
            "the Claude module names {forbidden}, which belongs to another vendor"
        );
    }
}

/// EAC-FR-23, the half the format change added — a long turn's whole event
/// stream still fits inside the capture bound, and the envelope still comes out
/// of it.
///
/// The regression this pins is a quiet one: the bound used to hold one small
/// result document, and the stream that replaced it carries every tool result
/// the agent read. A bound left at the document's size turns a long, successful
/// turn into `invalid_structured_output` for no reason but its length — and the
/// longer the turn, the more likely it is, which is exactly backwards.
#[test]
fn a_long_turns_whole_event_stream_fits_inside_the_capture_bound() {
    let harness = harness_for("claude_code");

    // Twelve megabytes of progress before the result: past what one document
    // ever needed, and well within what a half-hour turn reading files emits.
    let noise = "n".repeat(60 * 1024);
    let mut stream = String::new();
    for i in 0..200 {
        stream.push_str(
            &json!({
                "type": "user",
                "message": { "content": [{ "type": "tool_result", "content": format!("{i}{noise}") }] }
            })
            .to_string(),
        );
        stream.push('\n');
    }
    assert!(
        stream.len() > 8 * 1024 * 1024,
        "the fixture must outgrow the bound this used to have"
    );
    stream.push_str(&claude_result_line(&envelope_json("success")));
    stream.push('\n');
    assert!(stream.len() < LIMIT_STDOUT, "and stay inside the one it has");

    let runtime = RecordingRuntime::replying(&stream);
    let outcome = run(&harness, runtime, task("go")).expect("runs");

    assert!(
        !outcome.stdout.truncated,
        "the stream was cut short and the turn was failed for its length"
    );
    assert_eq!(outcome.process_outcome, ProcessOutcome::Completed);
    assert_eq!(
        outcome.response.expect("an envelope").summary,
        "did the thing"
    );
}

/// EAC-FR-32, the property the whole seam exists for — a line reaches a watcher
/// **while the run is still going**, not when it ends.
///
/// Every other observer test in this file runs through a double, and a double
/// replays lines at whatever moment it chooses. This one runs a real child that
/// writes one line and then does nothing for a long time: an observer that only
/// heard at exit would hear nothing at all here, which is precisely the failure
/// the single-document output format used to guarantee.
#[test]
fn a_line_reaches_a_watcher_while_the_run_is_still_going() {
    use std::sync::mpsc;

    struct FirstLine(StdMutex<Option<mpsc::Sender<String>>>);
    impl StreamObserver for FirstLine {
        fn line(&self, _channel: StreamChannel, bytes: &[u8], _whole: bool) {
            if bytes.is_empty() {
                return;
            }
            if let Some(tell) = self.0.lock().unwrap().take() {
                let _ = tell.send(String::from_utf8_lossy(bytes).into_owned());
            }
        }
    }

    let (tell, heard) = mpsc::channel();
    let observer = FirstLine(StdMutex::new(Some(tell)));
    let cancel = CancellationToken::new();
    let runtime = HostDockerCli::with_program("/bin/sh");

    // The child says one thing and then holds the container open far longer than
    // this test will wait.
    let request_cancel = cancel.clone();
    let run = async {
        runtime
            .run(RunRequest {
                argv: &[
                    "-c".to_string(),
                    "printf 'MARKER-EARLY\\n'; sleep 30".to_string(),
                ],
                container: None,
                env: &BTreeMap::new(),
                stdin: b"",
                timeout: Duration::from_secs(60),
                cancel: request_cancel,
                stdout_limit: 4096,
                stderr_limit: 4096,
                observer: Some(&observer),
            })
            .await
    };

    // Wait for the line on another thread, then end the run. A `recv_timeout`
    // that expires is the failure being tested for: the child is still running,
    // so anything that waits for exit has heard nothing.
    let watcher = std::thread::spawn(move || {
        let line = heard.recv_timeout(Duration::from_secs(20));
        cancel.cancel();
        line
    });

    let outcome = block_on(run).expect("the child ran");
    let line = watcher.join().expect("the watcher thread");

    assert_eq!(
        line.as_deref(),
        Ok("MARKER-EARLY"),
        "nothing reached the watcher until the run ended"
    );
    assert_eq!(outcome.end, RunEnd::Cancelled);
}

/// EAC-FR-32 — observation continues past the capture bound.
///
/// What a run is doing while it overruns its capture is exactly what somebody
/// watching it wants to see, and it is the moment a reader most needs it: a turn
/// that produced eight megabytes of output is a turn that has gone wrong. The
/// capture keeps its prefix and says it was cut; the watcher keeps hearing.
#[test]
fn a_watcher_keeps_hearing_after_the_capture_bound_is_reached() {
    #[derive(Default)]
    struct Heard(StdMutex<Vec<String>>);
    impl StreamObserver for Heard {
        fn line(&self, _channel: StreamChannel, bytes: &[u8], _whole: bool) {
            if !bytes.is_empty() {
                self.0
                    .lock()
                    .unwrap()
                    .push(String::from_utf8_lossy(bytes).into_owned());
            }
        }
    }

    let observer = Heard::default();
    let runtime = HostDockerCli::with_program("/bin/sh");
    let outcome = block_on(runtime.run(RunRequest {
        argv: &[
            "-c".to_string(),
            "for i in 1 2 3 4 5 6 7 8 9 10; do printf 'line-%s\\n' \"$i\"; done".to_string(),
        ],
        container: None,
        env: &BTreeMap::new(),
        stdin: b"",
        timeout: Duration::from_secs(30),
        cancel: CancellationToken::new(),
        // Room for two lines and no more.
        stdout_limit: 14,
        stderr_limit: 4096,
        observer: Some(&observer),
    }))
    .expect("the child ran");

    let heard = observer.0.lock().unwrap().clone();
    assert_eq!(heard.len(), 10, "the watcher stopped at the capture bound");
    assert_eq!(heard.first().map(String::as_str), Some("line-1"));
    assert_eq!(heard.last().map(String::as_str), Some("line-10"));
    // And the capture is still bounded and still says it was cut.
    assert!(outcome.stdout.truncated);
    assert!(outcome.stdout.bytes.len() <= 14);
}

/// EAC-FR-32 — an observer holding bytes back is flushed at end of stream.
///
/// A piece delivered at the reassembly bound leaves the executor holding its
/// tail against a credential split across it. A stream that ends exactly there
/// has nothing left to prompt a delivery, so end of stream must prompt one — or
/// the last bytes the agent wrote are held for ever and never seen.
#[test]
fn the_end_of_a_stream_flushes_what_an_observer_was_holding() {
    #[derive(Default)]
    struct Pieces(StdMutex<Vec<(usize, bool)>>);
    impl StreamObserver for Pieces {
        fn line(&self, _channel: StreamChannel, bytes: &[u8], whole: bool) {
            self.0.lock().unwrap().push((bytes.len(), whole));
        }
    }

    let observer = Pieces::default();
    let runtime = HostDockerCli::with_program("/bin/sh");
    // Exactly the reassembly bound, with no line ending anywhere and nothing
    // after it: the case where `pending` is empty at EOF.
    block_on(runtime.run(RunRequest {
        argv: &[
            "-c".to_string(),
            format!(
                "head -c {} /dev/zero | tr '\\0' 'y'",
                LIMIT_OBSERVED_LINE
            ),
        ],
        container: None,
        env: &BTreeMap::new(),
        stdin: b"",
        timeout: Duration::from_secs(60),
        cancel: CancellationToken::new(),
        stdout_limit: LIMIT_OBSERVED_LINE * 2,
        stderr_limit: 4096,
        observer: Some(&observer),
    }))
    .expect("the child ran");

    let pieces = observer.0.lock().unwrap().clone();
    // One piece at the bound, and then the end-of-stream delivery that lets an
    // observer flush whatever it was holding back.
    assert_eq!(pieces.first(), Some(&(LIMIT_OBSERVED_LINE, false)));
    assert!(
        pieces.iter().any(|(_, whole)| *whole),
        "end of stream never told the observer it had arrived: {pieces:?}"
    );
}

/// EAC-FR-35: the response contract an agent receives carries no authoring
/// comment, while the file it comes from keeps its own.
#[test]
fn the_response_contract_carries_no_authoring_comment() {
    const FILE: &str = include_str!("../../../../../resources/prompts/agent-exec/response-contract.md");

    // The file carries one today, so this is testing something.
    assert!(
        FILE.contains("<!--"),
        "the response-contract file is expected to carry an authoring comment",
    );

    let contract = RESPONSE_CONTRACT.as_str();
    assert!(
        !contract.contains("<!--") && !contract.contains("-->"),
        "a comment delimiter reaches the agent",
    );
    // Nothing of the comment's own content survives.
    let opened = FILE.find("<!--").expect("the comment");
    let closed = FILE.find("-->").expect("its end");
    for line in FILE[opened + 4..closed].lines().map(str::trim) {
        if line.len() > 20 {
            assert!(!contract.contains(line), "a comment line reaches the agent: {line:?}");
        }
    }
    // What is left begins at its first real word, and the rest of the file is
    // still there.
    assert_eq!(contract, contract.trim_start());
    assert!(!contract.trim().is_empty());
    let tail = FILE[closed + 3..].trim();
    assert!(
        contract.contains(tail),
        "the contract beyond the comment was altered",
    );

    // And what actually reaches stdin holds none of it either.
    let bytes = task("do the work")
        .to_stdin_bytes()
        .expect("the document");
    let document = String::from_utf8(bytes).expect("utf-8");
    assert!(!document.contains("<!--") && !document.contains("-->"));
}
