id = "1a087789112-0000-e3495b32"
name = "Discussion and multiple questions"
promptPath = "Discussion and multiple questions.md"
status = "active"
createdAt = "2026-09-09T18:40:20Z"
updatedAt = "2026-09-10T12:38:25Z"
