id = "19fef3b5383-00a6-88d94bf2"
scope = "project"
body = "Drafts panel should group  drafts by type, with “archived” or “implemented” at the bottom."
created_at = "2026-08-11T05:11:10Z"
updated_at = "2026-08-11T05:12:07Z"
