id = "19ff1604e04-0036-cb71096f"
scope = "project"
body = "There should be a way to collapse open discussion in the attached mode."
created_at = "2026-08-11T15:10:48Z"
updated_at = "2026-08-11T15:11:10Z"
