id = "19ff62e020a-0020-fd79af2f"
scope = "project"
body = "All input tabs must support Cmd+Enter/Ctrl+Enter, including Notes and Discussion start"
created_at = "2026-08-12T13:33:58Z"
updated_at = "2026-08-12T13:34:21Z"
