id = "19fff507a84-000f-b4221a3b"
scope = "project"
body = """
Default visualization of the “Draft change proposal” should be final and rich mode.

When Discussion window is in detached mode and Draft change proposal pops up - the chat window should be minimized. Once the decision is made and draft change either approved or rejected - chat window should be restored back in detached mode."""
created_at = "2026-08-14T08:08:12Z"
updated_at = "2026-08-14T08:16:38Z"
