id = "1a01dbcf500-00a1-127080ed"
scope = "project"
body = "We need a better tab in detached chat mode. It should allow resolving thread and exporting the chat as plain text."
created_at = "2026-08-20T05:55:17Z"
updated_at = "2026-08-20T05:56:02Z"
